- hosts: all
  become: true
  gather_facts: false

  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get update && sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup

  roles:
    - { role: cloudwatch, tags: cloudwatch }
    - { role: firewall, tags: firewall }
    - { role: security, tags: security }
    - { role: nginx, tags: nginx}
    - { role: nginx_harden, tags: nginx_harden}
    - { role: clamav, tags: clamav}

  tasks:
    - name: Cloning Public Rvsharma Page.
      git:
        repo: 'https://github.com/Rahulsharma0810/rvsharma.com.git'
        dest: /var/www/eltropydemo.rvsharma.com
        version: main
