---
# tasks file for aws monitoring
    - name: install nessesagy package
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - unzip
        - libwww-perl
        - libdatetime-perl

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
        dest: /root
        remote_src: yes


    - name: copy awscreds.conf
      copy:
        src: awscreds.conf
        dest: /root/aws-scripts-mon/awscreds.conf
        owner: root
        group: root
        mode: 0600

    - name: create crontab job
      cron:
        name: "aws monitoring"
        user: "root"
        minute: "*/1"
        job: "/root/aws-scripts-mon/mon-put-instance-data.pl --mem-used-incl-cache-buff --mem-util --disk-space-util --disk-path=/ --from-cron"